### ISSUE TITLE
Remove “Open last bookmark” Quick Action

### ISSUE THREAD

**Issue by chrmod** [cliqz/user-agent-ios#582]
![0D91FEBE-EC4F-4E73-96F2-8C39DF7808C3](https://user-images.githubusercontent.com/1228153/70354400-b8dab980-186f-11ea-9acc-10bc93dc7e20.png)
It may not be a bug but previously registered Quick Action was not cleared. 

How about we clear all Quick Actions?

**Comment by pavel-cliqz** [comment]
@chrmod super weird problem. 
The thing is that in order to maintain this list there is UIApplicationShortcutItems which defines a list of actions with icons. And obviously there is no such think like open Bookmark there. That's why in normal circumstances no one sees that. But somehow for some weird cases it adds that item. Can it be that CD is modifying info plist in that way. I checked fastlane, couldn't see anything which might cause to that. But I don't see the full configuration of jenkins. I can imagine that in CD could be some old logic left which is modifying the info plist and adding that option. But here the question will be, why not always? So it's really a mystery...

**Comment by pavel-cliqz** [comment]
you can also add them dynamically  using UIMutableApplicationShortcutItem and adding it to UIApplicatio shortcutItems. But this code is removed from out app long time ago. So it's really strange and weird why it's appearing. The button, text and the code is not there for a long time

**Comment by pavel-cliqz** [comment]
It should be some system bug, as it doesn't go to production. To make sure we keep it empty we could set this in app launch UIApplication.shortcutItems = [].

**Comment by chrmod** [comment]
In the old app version that is what I've done to clear broken quick actions: https://github.com/ghostery/browser-ios/commit/d4defbd9e1615f46280a4ff0d96de6c6051681d2#diff-19fd1a6fe4b2f78eb457726f366733e0R371
